let Store = {
	list: [{
		name: "张三",
		age: "27",
		male: "男",
		address: "云南省昆明市广福城",
		mobile: "13888888888",
		profession: "软件工程师",
		position: "开发"
	}, {
		name: "张三",
		age: "27",
		male: "男",
		address: "云南省昆明市广福城",
		mobile: "13888888888",
		profession: "软件工程师",
		position: "开发"
	}, {
		name: "张三",
		age: "27",
		male: "男",
		address: "云南省昆明市广福城",
		mobile: "13888888888",
		profession: "软件工程师",
		position: "开发"
	}, {
		name: "张三",
		age: "27",
		male: "男",
		address: "云南省昆明市广福城",
		mobile: "13888888888",
		profession: "软件工程师",
		position: "开发"
	}, {
		name: "张三",
		age: "27",
		male: "男",
		address: "云南省昆明市广福城",
		mobile: "13888888888",
		profession: "软件工程师",
		position: "开发"
	}, {
		name: "张三",
		age: "27",
		male: "男",
		address: "云南省昆明市广福城",
		mobile: "13888888888",
		profession: "软件工程师",
		position: "开发"
	}, {
		name: "张三",
		age: "27",
		male: "男",
		address: "云南省昆明市广福城",
		mobile: "13888888888",
		profession: "软件工程师",
		position: "开发"
	}, {
		name: "张三",
		age: "27",
		male: "男",
		address: "云南省昆明市广福城",
		mobile: "13888888888",
		profession: "软件工程师",
		position: "开发"
	}, {
		name: "张三",
		age: "27",
		male: "男",
		address: "云南省昆明市广福城",
		mobile: "13888888888",
		profession: "软件工程师",
		position: "开发"
	}, {
		name: "张三",
		age: "27",
		male: "男",
		address: "云南省昆明市广福城",
		mobile: "13888888888",
		profession: "软件工程师",
		position: "开发"
	}, {
		name: "张三",
		age: "27",
		male: "男",
		address: "云南省昆明市广福城",
		mobile: "13888888888",
		profession: "软件工程师",
		position: "开发"
	}, {
		name: "张三",
		age: "27",
		male: "男",
		address: "云南省昆明市广福城",
		mobile: "13888888888",
		profession: "软件工程师",
		position: "开发"
	}, {
		name: "张三",
		age: "27",
		male: "男",
		address: "云南省昆明市广福城",
		mobile: "13888888888",
		profession: "软件工程师",
		position: "开发"
	}, {
		name: "张三",
		age: "27",
		male: "男",
		address: "云南省昆明市广福城",
		mobile: "13888888888",
		profession: "软件工程师",
		position: "开发"
	}, {
		name: "张三",
		age: "27",
		male: "男",
		address: "云南省昆明市广福城",
		mobile: "13888888888",
		profession: "软件工程师",
		position: "开发"
	}, {
		name: "张三",
		age: "27",
		male: "男",
		address: "云南省昆明市广福城",
		mobile: "13888888888",
		profession: "软件工程师",
		position: "开发"
	}, {
		name: "张三",
		age: "27",
		male: "男",
		address: "云南省昆明市广福城",
		mobile: "13888888888",
		profession: "软件工程师",
		position: "开发"
	}, {
		name: "张三",
		age: "27",
		male: "男",
		address: "云南省昆明市广福城",
		mobile: "13888888888",
		profession: "软件工程师",
		position: "开发"
	}, {
		name: "张三",
		age: "27",
		male: "男",
		address: "云南省昆明市广福城",
		mobile: "13888888888",
		profession: "软件工程师",
		position: "开发"
	}, {
		name: "张三",
		age: "27",
		male: "男",
		address: "云南省昆明市广福城",
		mobile: "13888888888",
		profession: "软件工程师",
		position: "开发"
	}, {
		name: "张三",
		age: "27",
		male: "男",
		address: "云南省昆明市广福城",
		mobile: "13888888888",
		profession: "软件工程师",
		position: "开发"
	}, {
		name: "张三",
		age: "27",
		male: "男",
		address: "云南省昆明市广福城",
		mobile: "13888888888",
		profession: "软件工程师",
		position: "开发"
	}, {
		name: "张三",
		age: "27",
		male: "男",
		address: "云南省昆明市广福城",
		mobile: "13888888888",
		profession: "软件工程师",
		position: "开发"
	}, {
		name: "张三",
		age: "27",
		male: "男",
		address: "云南省昆明市广福城",
		mobile: "13888888888",
		profession: "软件工程师",
		position: "开发"
	}, {
		name: "张三",
		age: "27",
		male: "男",
		address: "云南省昆明市广福城",
		mobile: "13888888888",
		profession: "软件工程师",
		position: "开发"
	}, {
		name: "张三",
		age: "27",
		male: "男",
		address: "云南省昆明市广福城",
		mobile: "13888888888",
		profession: "软件工程师",
		position: "开发"
	}, {
		name: "张三",
		age: "27",
		male: "男",
		address: "云南省昆明市广福城",
		mobile: "13888888888",
		profession: "软件工程师",
		position: "开发"
	}, {
		name: "李四",
		age: "27",
		male: "男",
		address: "云南省昆明市广福城",
		mobile: "13888888888",
		profession: "软件工程师",
		position: "开发"
	}],
	getList() {
		return this.list;
	}
}

export default Store